// <auto-generated />
using Infrastructure.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PrincipalDbContext))]
    [Migration("20240819232616_cascade-dummy-b")]
    partial class cascadedummyb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EntidadDummy", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntidadDummyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EntidadDummyId");

                    b.ToTable("EntidadDummyB", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntidadDummy.Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EntidadDummy.Id")
                        .IsUnique();

                    b.ToTable("EntidadDummyC", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyB", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", "EntidadDummy")
                        .WithMany("DummiesB")
                        .HasForeignKey("EntidadDummyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntidadDummy");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyC", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", "EntidadDummy")
                        .WithOne("DummyC")
                        .HasForeignKey("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyC", "EntidadDummy.Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntidadDummy");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", b =>
                {
                    b.Navigation("DummiesB");

                    b.Navigation("DummyC")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
