// <auto-generated />
using System;
using Infrastructure.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PrincipalDbContext))]
    [Migration("20241220000156_turnos")]
    partial class turnos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EntidadDummy", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntidadDummyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EntidadDummyId");

                    b.ToTable("EntidadDummyB", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntidadDummyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EntidadDummyId")
                        .IsUnique();

                    b.ToTable("EntidadDummyC", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EntidadDummyD", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Turnos.Entities.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Turno", (string)null);
                });

            modelBuilder.Entity("EntidadDummyEntidadDummyD", b =>
                {
                    b.Property<int>("DummiesAId")
                        .HasColumnType("int");

                    b.Property<int>("DummiesDId")
                        .HasColumnType("int");

                    b.HasKey("DummiesAId", "DummiesDId");

                    b.HasIndex("DummiesDId");

                    b.ToTable("EntidadDummyDEntidadDummy", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.ContactoTelefonico", "Contacto", b1 =>
                        {
                            b1.Property<int>("EntidadDummyId")
                                .HasColumnType("int");

                            b1.Property<string>("Extension")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NumeroTelefono")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("Tipo")
                                .HasColumnType("int");

                            b1.HasKey("EntidadDummyId");

                            b1.ToTable("EntidadDummy");

                            b1.WithOwner()
                                .HasForeignKey("EntidadDummyId");
                        });

                    b.Navigation("Contacto");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyB", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", "EntidadDummy")
                        .WithMany("DummiesB")
                        .HasForeignKey("EntidadDummyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntidadDummy");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyC", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", "EntidadDummy")
                        .WithOne("DummyC")
                        .HasForeignKey("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyC", "EntidadDummyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntidadDummy");
                });

            modelBuilder.Entity("EntidadDummyEntidadDummyD", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", null)
                        .WithMany()
                        .HasForeignKey("DummiesAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyD", null)
                        .WithMany()
                        .HasForeignKey("DummiesDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", b =>
                {
                    b.Navigation("DummiesB");

                    b.Navigation("DummyC")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
