// <auto-generated />
using System;
using Infrastructure.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PrincipalDbContext))]
    partial class PrincipalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EntidadDummy", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntidadDummyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EntidadDummyId");

                    b.ToTable("EntidadDummyB", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntidadDummyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EntidadDummyId")
                        .IsUnique();

                    b.ToTable("EntidadDummyC", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EntidadDummyD", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.HistoriasClinicas.Entities.HistoriaClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CansancioAlCaminar")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Embarazo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("HistoriaClinica", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.ObrasSociales.Entities.ObraSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ObraSocial", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Odontogramas.Entities.CaraDental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("CaraDentaria")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PiezaDentalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PiezaDentalId");

                    b.ToTable("CaraDental", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Odontogramas.Entities.Odontograma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Odontograma", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Odontogramas.Entities.OdontogramaCaraDental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaraDentalId")
                        .HasColumnType("int");

                    b.Property<string>("ColorHexadecimal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPrestacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("NomencladorId")
                        .HasColumnType("int");

                    b.Property<int?>("ObraSocialId")
                        .HasColumnType("int");

                    b.Property<int>("PiezaDentalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaraDentalId");

                    b.HasIndex("NomencladorId");

                    b.HasIndex("ObraSocialId");

                    b.HasIndex("PiezaDentalId");

                    b.ToTable("OdontogramaCaraDental", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Odontogramas.Entities.OdontogramaPiezaDental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OdontogramaId")
                        .HasColumnType("int");

                    b.Property<int>("PiezaDentalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OdontogramaId");

                    b.HasIndex("PiezaDentalId");

                    b.ToTable("OdontogramaPiezaDental", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Odontogramas.Entities.PiezaDental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Cuadrante")
                        .HasColumnType("int");

                    b.Property<bool>("DenticionPermanente")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte>("NumeroPieza")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("NumeroPieza")
                        .IsUnique()
                        .HasDatabaseName("IX_PiezaDental_NumeroPieza");

                    b.ToTable("PiezaDental", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Pacientes.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ObraSocialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObraSocialId");

                    b.ToTable("Paciente", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Prestaciones.Entities.Nomenclador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoNacional")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ColorHexSugerido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Importe")
                        .HasPrecision(13, 2)
                        .HasColumnType("decimal(13,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereCara")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ObraSocialId");

                    b.ToTable("Nomenclador", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Turnos.Entities.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Turno", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Usuarios.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Rol")
                        .HasColumnType("tinyint");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("EntidadDummyEntidadDummyD", b =>
                {
                    b.Property<int>("DummiesAId")
                        .HasColumnType("int");

                    b.Property<int>("DummiesDId")
                        .HasColumnType("int");

                    b.HasKey("DummiesAId", "DummiesDId");

                    b.HasIndex("DummiesDId");

                    b.ToTable("EntidadDummyDEntidadDummy", (string)null);
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.ContactoTelefonico", "Contacto", b1 =>
                        {
                            b1.Property<int>("EntidadDummyId")
                                .HasColumnType("int");

                            b1.Property<string>("Extension")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NumeroTelefono")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("Tipo")
                                .HasColumnType("int");

                            b1.HasKey("EntidadDummyId");

                            b1.ToTable("EntidadDummy");

                            b1.WithOwner()
                                .HasForeignKey("EntidadDummyId");
                        });

                    b.Navigation("Contacto");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyB", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", "EntidadDummy")
                        .WithMany("DummiesB")
                        .HasForeignKey("EntidadDummyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntidadDummy");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyC", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", "EntidadDummy")
                        .WithOne("DummyC")
                        .HasForeignKey("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyC", "EntidadDummyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntidadDummy");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.HistoriasClinicas.Entities.HistoriaClinica", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.Pacientes.Entities.Paciente", "Paciente")
                        .WithOne("HistoriaClinica")
                        .HasForeignKey("Domain.FunctionalUnits.HistoriasClinicas.Entities.HistoriaClinica", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.RespuestaConDetalle", "Alergias", b1 =>
                        {
                            b1.Property<int>("HistoriaClinicaId")
                                .HasColumnType("int");

                            b1.Property<string>("Detalle")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)");

                            b1.Property<bool>("Si")
                                .HasColumnType("bit");

                            b1.HasKey("HistoriaClinicaId");

                            b1.ToTable("HistoriaClinica");

                            b1.WithOwner()
                                .HasForeignKey("HistoriaClinicaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.RespuestaConDetalle", "AnestesiasPrevias", b1 =>
                        {
                            b1.Property<int>("HistoriaClinicaId")
                                .HasColumnType("int");

                            b1.Property<string>("Detalle")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)");

                            b1.Property<bool>("Si")
                                .HasColumnType("bit");

                            b1.HasKey("HistoriaClinicaId");

                            b1.ToTable("HistoriaClinica");

                            b1.WithOwner()
                                .HasForeignKey("HistoriaClinicaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Habito", "Bebe", b1 =>
                        {
                            b1.Property<int>("HistoriaClinicaId")
                                .HasColumnType("int");

                            b1.Property<int?>("Cantidad")
                                .HasColumnType("int");

                            b1.Property<bool>("Tiene")
                                .HasColumnType("bit");

                            b1.HasKey("HistoriaClinicaId");

                            b1.ToTable("HistoriaClinica");

                            b1.WithOwner()
                                .HasForeignKey("HistoriaClinicaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Habito", "Fuma", b1 =>
                        {
                            b1.Property<int>("HistoriaClinicaId")
                                .HasColumnType("int");

                            b1.Property<int?>("Cantidad")
                                .HasColumnType("int");

                            b1.Property<bool>("Tiene")
                                .HasColumnType("bit");

                            b1.HasKey("HistoriaClinicaId");

                            b1.ToTable("HistoriaClinica");

                            b1.WithOwner()
                                .HasForeignKey("HistoriaClinicaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.RespuestaConDetalle", "IntervencionesUlt2Anios", b1 =>
                        {
                            b1.Property<int>("HistoriaClinicaId")
                                .HasColumnType("int");

                            b1.Property<string>("Detalle")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)");

                            b1.Property<bool>("Si")
                                .HasColumnType("bit");

                            b1.HasKey("HistoriaClinicaId");

                            b1.ToTable("HistoriaClinica");

                            b1.WithOwner()
                                .HasForeignKey("HistoriaClinicaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.RespuestaConDetalle", "MedicacionActual", b1 =>
                        {
                            b1.Property<int>("HistoriaClinicaId")
                                .HasColumnType("int");

                            b1.Property<string>("Detalle")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)");

                            b1.Property<bool>("Si")
                                .HasColumnType("bit");

                            b1.HasKey("HistoriaClinicaId");

                            b1.ToTable("HistoriaClinica");

                            b1.WithOwner()
                                .HasForeignKey("HistoriaClinicaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.RespuestaConDetalle", "SangradoExcesivo", b1 =>
                        {
                            b1.Property<int>("HistoriaClinicaId")
                                .HasColumnType("int");

                            b1.Property<string>("Detalle")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)");

                            b1.Property<bool>("Si")
                                .HasColumnType("bit");

                            b1.HasKey("HistoriaClinicaId");

                            b1.ToTable("HistoriaClinica");

                            b1.WithOwner()
                                .HasForeignKey("HistoriaClinicaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.RespuestaConDetalle", "TratamientoMedico", b1 =>
                        {
                            b1.Property<int>("HistoriaClinicaId")
                                .HasColumnType("int");

                            b1.Property<string>("Detalle")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)");

                            b1.Property<bool>("Si")
                                .HasColumnType("bit");

                            b1.HasKey("HistoriaClinicaId");

                            b1.ToTable("HistoriaClinica");

                            b1.WithOwner()
                                .HasForeignKey("HistoriaClinicaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.RespuestaConFecha", "Radiografias", b1 =>
                        {
                            b1.Property<int>("HistoriaClinicaId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("Fecha")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Si")
                                .HasColumnType("bit");

                            b1.HasKey("HistoriaClinicaId");

                            b1.ToTable("HistoriaClinica");

                            b1.WithOwner()
                                .HasForeignKey("HistoriaClinicaId");
                        });

                    b.Navigation("Alergias")
                        .IsRequired();

                    b.Navigation("AnestesiasPrevias")
                        .IsRequired();

                    b.Navigation("Bebe")
                        .IsRequired();

                    b.Navigation("Fuma")
                        .IsRequired();

                    b.Navigation("IntervencionesUlt2Anios")
                        .IsRequired();

                    b.Navigation("MedicacionActual")
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Radiografias")
                        .IsRequired();

                    b.Navigation("SangradoExcesivo")
                        .IsRequired();

                    b.Navigation("TratamientoMedico")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Odontogramas.Entities.CaraDental", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.Odontogramas.Entities.PiezaDental", "PiezaDental")
                        .WithMany("CarasDentales")
                        .HasForeignKey("PiezaDentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PiezaDental");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Odontogramas.Entities.Odontograma", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.Pacientes.Entities.Paciente", "Paciente")
                        .WithMany("Odontogramas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Odontogramas.Entities.OdontogramaCaraDental", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.Odontogramas.Entities.CaraDental", "CaraDental")
                        .WithMany()
                        .HasForeignKey("CaraDentalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.FunctionalUnits.Prestaciones.Entities.Nomenclador", "Nomenclador")
                        .WithMany()
                        .HasForeignKey("NomencladorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.FunctionalUnits.ObrasSociales.Entities.ObraSocial", "ObraSocial")
                        .WithMany()
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.FunctionalUnits.Odontogramas.Entities.OdontogramaPiezaDental", "PiezaDental")
                        .WithMany("CarasDentales")
                        .HasForeignKey("PiezaDentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaraDental");

                    b.Navigation("Nomenclador");

                    b.Navigation("ObraSocial");

                    b.Navigation("PiezaDental");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Odontogramas.Entities.OdontogramaPiezaDental", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.Odontogramas.Entities.Odontograma", "Odontograma")
                        .WithMany("PiezasDentales")
                        .HasForeignKey("OdontogramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.FunctionalUnits.Odontogramas.Entities.PiezaDental", "PiezaDental")
                        .WithMany()
                        .HasForeignKey("PiezaDentalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Odontograma");

                    b.Navigation("PiezaDental");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Pacientes.Entities.Paciente", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.ObrasSociales.Entities.ObraSocial", "ObraSocial")
                        .WithMany()
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Prestaciones.Entities.Nomenclador", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.ObrasSociales.Entities.ObraSocial", "ObraSocial")
                        .WithMany()
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Turnos.Entities.Turno", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.Pacientes.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("EntidadDummyEntidadDummyD", b =>
                {
                    b.HasOne("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", null)
                        .WithMany()
                        .HasForeignKey("DummiesAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummyD", null)
                        .WithMany()
                        .HasForeignKey("DummiesDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.FunctionalUnits.EntidadDummies.Entities.EntidadDummy", b =>
                {
                    b.Navigation("DummiesB");

                    b.Navigation("DummyC")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Odontogramas.Entities.Odontograma", b =>
                {
                    b.Navigation("PiezasDentales");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Odontogramas.Entities.OdontogramaPiezaDental", b =>
                {
                    b.Navigation("CarasDentales");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Odontogramas.Entities.PiezaDental", b =>
                {
                    b.Navigation("CarasDentales");
                });

            modelBuilder.Entity("Domain.FunctionalUnits.Pacientes.Entities.Paciente", b =>
                {
                    b.Navigation("HistoriaClinica");

                    b.Navigation("Odontogramas");
                });
#pragma warning restore 612, 618
        }
    }
}
